fs/pstore: fix compilation warning
  fs/pstore/ram.c: In function 'ramoops_probe':
  fs/pstore/ram.c:526:6: error: void value not ignored as it ought to be

Change-Id: I8ad52a8955486df59bb8f7d09757fcb8b1a4e036
Signed-off-by: Patrick Tjin <pattjin@google.com>
(cherry picked from commit d1b1ff2acd18197a56542d1015b39c810d136cc0)